version: '3'
services:
    amqp_sender_app:
      image: ykizilay/amqp_sender_app:0.0.2
      container_name: amqp_sender_app
      ports:
         - 8080:8080 
      environment:
        - spring.rabbitmq.host=172.20.0.1
        - spring.rabbitmq.port=5672
        - spring.rabbitmq.username=ykizilay
        - spring.rabbitmq.password=1234
